import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Header } from '@/components'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

const TableComponent = dynamic(() => import("remote/table"), {
  ssr: false,
  suspense: true
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Micro Frontend CRUD Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Header/>
        <section style={{display: 'flex', justifyContent: 'center', alignItems: 'center', maxWidth: '100dvw', padding: 10, marginTop: 100, marginBottom: 50}}>
          <TableComponent/>
        </section>
      </main>
    </>
  )
}
